2019-06-20T16:49:46|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "Microscope_app.py", line 48, in <module>
    app = MicroscopeApp(sys.argv)
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 338, in __init__
    self.setup()
  File "Microscope_app.py", line 19, in setup
    self.add_hardware(PicoHarp(HW))
NameError: name 'PicoHarp' is not defined

